package raman.audio.shared_transition

object DataSource {

    val items = mutableListOf(
        GalleryItem(
            1,
            "http://tree-pictures.com/common-hackberry-s.jpg"
        ),
        GalleryItem(
            2,
            "http://wallperio.com/data/out/422/romantic-pics_620417806.jpg"
        ),
        GalleryItem(
            3,
            "http://tree-pictures.com/common-hackberry-s.jpg"
        ),
        GalleryItem(
            4,
            "http://wallperio.com/data/out/422/romantic-pics_620417806.jpg"
        ),
        GalleryItem(
            5,
            "http://tree-pictures.com/common-hackberry-s.jpg"
        ),
        GalleryItem(
            6,
            "http://wallperio.com/data/out/422/romantic-pics_620417806.jpg"
        ),
        GalleryItem(
            7,
            "http://tree-pictures.com/common-hackberry-s.jpg"
        ),
        GalleryItem(
            8,
            "https://www.landscapesbypatricksteel.co.uk/wp-content/uploads/2015/01/settling_down_thumb-400x400.jpg"
        ),
        GalleryItem(
            9,
            "http://tree-pictures.com/common-hackberry-s.jpg"
        ),
        GalleryItem(
            10,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            11,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            12,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            13,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            14,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            15,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            16,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            17,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            18,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            19,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            20,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            21,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            22,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            23,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            24,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            25,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            25,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            27,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            28,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            29,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            30,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            31,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            32,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            33,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            34,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        ),
        GalleryItem(
            35,
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI1HNfK4BtJZvqyCOhGma7K68wIK3orhDvDctjtvxN_PcvL7D6"
        )
    )
}